services:
  db:
    image: mysql:8.0
    container_name: cashforce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cashforce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./src/assets/cashforce_dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    networks:
      - mysql_net

networks:
  mysql_net:
    driver: bridge

